"""Add learning journey and steps

Revision ID: 31c9c08c60aa
Revises: ccc088e61eb9
Create Date: 2026-04-17 15:02:00.922470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c9c08c60aa'
down_revision: Union[str, Sequence[str], None] = 'ccc088e61eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('journey_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['learning_journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('learner_profiles', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('learner_profiles', sa.Column('current_journey_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_profiles', 'current_journey_id')
    op.drop_column('learner_profiles', 'points')
    op.drop_table('journey_steps')
    op.drop_table('learning_journeys')
    # ### end Alembic commands ###
