"""Add CEFR models

Revision ID: 4d049b2f1532
Revises: 6030b794259a
Create Date: 2026-06-04 13:28:37.244436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d049b2f1532'
down_revision: Union[str, Sequence[str], None] = '6030b794259a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_stage',
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('public_level', sa.String(), nullable=True),
    sa.Column('stage_title', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('cefr_band', sa.String(), nullable=True),
    sa.Column('stage_group', sa.String(), nullable=True),
    sa.Column('descriptor_summary', sa.Text(), nullable=True),
    sa.Column('learner_profile', sa.Text(), nullable=True),
    sa.Column('exit_outcome', sa.Text(), nullable=True),
    sa.Column('next_stage_id', sa.String(), nullable=True),
    sa.Column('active_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['next_stage_id'], ['curriculum_stage.stage_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('function_tag',
    sa.Column('function_tag', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('function_tag')
    )
    op.create_table('grammar_tag',
    sa.Column('grammar_tag', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('progression_hint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('grammar_tag')
    )
    op.create_table('vocabulary_domain_tag',
    sa.Column('vocab_domain_tag', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vocab_domain_tag')
    )
    op.create_table('can_do_outcome',
    sa.Column('cando_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('descriptor_family', sa.String(), nullable=True),
    sa.Column('skill_area', sa.String(), nullable=True),
    sa.Column('can_do_statement', sa.Text(), nullable=True),
    sa.Column('critical_flag', sa.Boolean(), nullable=True),
    sa.Column('support_tolerance', sa.String(), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=True),
    sa.Column('transfer_required', sa.Boolean(), nullable=True),
    sa.Column('grammar_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('function_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_domain_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['curriculum_stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cando_id')
    )
    op.create_table('curriculum_module',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('module_order', sa.Integer(), nullable=True),
    sa.Column('module_title', sa.String(), nullable=True),
    sa.Column('primary_domain', sa.String(), nullable=True),
    sa.Column('communicative_focus', sa.Text(), nullable=True),
    sa.Column('descriptor_family_focus', sa.String(), nullable=True),
    sa.Column('grammar_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('function_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_domain_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scenario_family_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module_exit_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['curriculum_stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('error_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_nodes', sa.Integer(), nullable=True),
    sa.Column('current_node_index', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_gate',
    sa.Column('gate_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('next_stage_id', sa.String(), nullable=True),
    sa.Column('required_critical_mastery_pct', sa.Float(), nullable=True),
    sa.Column('required_review_stability_pct', sa.Float(), nullable=True),
    sa.Column('required_transfer_pass', sa.Boolean(), nullable=True),
    sa.Column('max_unresolved_blockers', sa.Integer(), nullable=True),
    sa.Column('support_dependence_rule', sa.String(), nullable=True),
    sa.Column('gate_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['curriculum_stage.stage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gate_id')
    )
    op.create_table('user_vocabulary_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_map_id', sa.UUID(), nullable=False),
    sa.Column('node_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_cando', sa.String(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['journey_map_id'], ['journey_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('task_index', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('alternative_attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_tasks')
    op.drop_table('nodes')
    op.drop_table('user_vocabulary_state')
    op.drop_table('promotion_gate')
    op.drop_table('journey_maps')
    op.drop_table('error_profile')
    op.drop_table('curriculum_module')
    op.drop_table('can_do_outcome')
    op.drop_table('vocabulary_domain_tag')
    op.drop_table('grammar_tag')
    op.drop_table('function_tag')
    op.drop_table('curriculum_stage')
    # ### end Alembic commands ###
