"""init

Revision ID: 5dcb8f069d00
Revises: 
Create Date: 2026-04-16 19:15:18.015702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dcb8f069d00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sessions_not_after_idx'), table_name='sessions', schema='auth')
    op.drop_index(op.f('sessions_oauth_client_id_idx'), table_name='sessions', schema='auth')
    op.drop_index(op.f('sessions_user_id_idx'), table_name='sessions', schema='auth')
    op.drop_index(op.f('user_id_created_at_idx'), table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index(op.f('sso_domains_domain_idx'), table_name='sso_domains', schema='auth')
    op.drop_index(op.f('sso_domains_sso_provider_id_idx'), table_name='sso_domains', schema='auth')
    op.drop_table('sso_domains', schema='auth')
    op.drop_index(op.f('audit_logs_instance_id_idx'), table_name='audit_log_entries', schema='auth')
    op.drop_table('audit_log_entries', schema='auth')
    op.drop_index(op.f('factor_id_created_at_idx'), table_name='mfa_factors', schema='auth')
    op.drop_index(op.f('mfa_factors_user_friendly_name_unique'), table_name='mfa_factors', schema='auth', postgresql_where="(TRIM(BOTH FROM friendly_name) <> ''::text)")
    op.drop_index(op.f('mfa_factors_user_id_idx'), table_name='mfa_factors', schema='auth')
    op.drop_index(op.f('unique_phone_factor_per_user'), table_name='mfa_factors', schema='auth')
    op.drop_table('mfa_factors', schema='auth')
    op.drop_table('skill_states')
    op.drop_index(op.f('bname'), table_name='buckets', schema='storage')
    op.drop_table('buckets', schema='storage')
    op.drop_index(op.f('buckets_analytics_unique_name_idx'), table_name='buckets_analytics', schema='storage', postgresql_where='(deleted_at IS NULL)')
    op.drop_table('buckets_analytics', schema='storage')
    op.drop_index(op.f('sso_providers_resource_id_idx'), table_name='sso_providers', schema='auth')
    op.drop_index(op.f('sso_providers_resource_id_pattern_idx'), table_name='sso_providers', schema='auth', postgresql_ops={'resource_id': 'text_pattern_ops'})
    op.drop_table('sso_providers', schema='auth')
    op.drop_index(op.f('messages_2026_04_15_inserted_at_topic_idx'), table_name='messages_2026_04_15', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_15', schema='realtime')
    op.drop_table('buckets_vectors', schema='storage')
    op.drop_table('schema_migrations', schema='realtime')
    op.drop_table('assessment_responses')
    op.drop_table('user_achievements')
    op.drop_index(op.f('saml_relay_states_created_at_idx'), table_name='saml_relay_states', schema='auth')
    op.drop_index(op.f('saml_relay_states_for_email_idx'), table_name='saml_relay_states', schema='auth')
    op.drop_index(op.f('saml_relay_states_sso_provider_id_idx'), table_name='saml_relay_states', schema='auth')
    op.drop_table('saml_relay_states', schema='auth')
    op.drop_index(op.f('saml_providers_sso_provider_id_idx'), table_name='saml_providers', schema='auth')
    op.drop_table('saml_providers', schema='auth')
    op.drop_table('s3_multipart_uploads_parts', schema='storage')
    op.drop_index(op.f('one_time_tokens_relates_to_hash_idx'), table_name='one_time_tokens', schema='auth', postgresql_using='hash')
    op.drop_index(op.f('one_time_tokens_token_hash_hash_idx'), table_name='one_time_tokens', schema='auth', postgresql_using='hash')
    op.drop_index(op.f('one_time_tokens_user_id_token_type_key'), table_name='one_time_tokens', schema='auth')
    op.drop_table('one_time_tokens', schema='auth')
    op.drop_index(op.f('ix_realtime_subscription_entity'), table_name='subscription', schema='realtime')
    op.drop_index(op.f('subscription_subscription_id_entity_filters_action_filter_key'), table_name='subscription', schema='realtime')
    op.drop_table('subscription', schema='realtime')
    op.drop_table('migrations', schema='storage')
    op.drop_table('learner_profiles')
    op.drop_table('assessments')
    op.drop_table('user_error_profiles')
    op.drop_table('question_bank_items')
    op.drop_index(op.f('idx_multipart_uploads_list'), table_name='s3_multipart_uploads', schema='storage')
    op.drop_table('s3_multipart_uploads', schema='storage')
    op.drop_index(op.f('vector_indexes_name_bucket_id_idx'), table_name='vector_indexes', schema='storage')
    op.drop_table('vector_indexes', schema='storage')
    op.drop_index(op.f('refresh_tokens_instance_id_idx'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('refresh_tokens_instance_id_user_id_idx'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('refresh_tokens_parent_idx'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('refresh_tokens_session_id_revoked_idx'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('refresh_tokens_updated_at_idx'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index(op.f('mfa_challenge_created_at_idx'), table_name='mfa_challenges', schema='auth')
    op.drop_table('mfa_challenges', schema='auth')
    op.drop_index(op.f('messages_2026_04_16_inserted_at_topic_idx'), table_name='messages_2026_04_16', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_16', schema='realtime')
    op.drop_index(op.f('messages_2026_04_14_inserted_at_topic_idx'), table_name='messages_2026_04_14', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_14', schema='realtime')
    op.drop_index(op.f('messages_2026_04_17_inserted_at_topic_idx'), table_name='messages_2026_04_17', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_17', schema='realtime')
    op.drop_table('users')
    op.drop_index(op.f('messages_2026_04_18_inserted_at_topic_idx'), table_name='messages_2026_04_18', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_18', schema='realtime')
    op.drop_table('schema_migrations', schema='auth')
    op.drop_index(op.f('webauthn_challenges_expires_at_idx'), table_name='webauthn_challenges', schema='auth')
    op.drop_index(op.f('webauthn_challenges_user_id_idx'), table_name='webauthn_challenges', schema='auth')
    op.drop_table('webauthn_challenges', schema='auth')
    op.drop_index(op.f('idx_oauth_client_states_created_at'), table_name='oauth_client_states', schema='auth')
    op.drop_table('oauth_client_states', schema='auth')
    op.drop_index(op.f('oauth_clients_deleted_at_idx'), table_name='oauth_clients', schema='auth')
    op.drop_table('oauth_clients', schema='auth')
    op.drop_index(op.f('bucketid_objname'), table_name='objects', schema='storage')
    op.drop_index(op.f('idx_objects_bucket_id_name'), table_name='objects', schema='storage')
    op.drop_index(op.f('idx_objects_bucket_id_name_lower'), table_name='objects', schema='storage')
    op.drop_index(op.f('name_prefix_search'), table_name='objects', schema='storage', postgresql_ops={'name': 'text_pattern_ops'})
    op.drop_table('objects', schema='storage')
    op.drop_index(op.f('oauth_auth_pending_exp_idx'), table_name='oauth_authorizations', schema='auth', postgresql_where="(status = 'pending'::auth.oauth_authorization_status)")
    op.drop_table('oauth_authorizations', schema='auth')
    op.drop_index(op.f('flow_state_created_at_idx'), table_name='flow_state', schema='auth')
    op.drop_index(op.f('idx_auth_code'), table_name='flow_state', schema='auth')
    op.drop_index(op.f('idx_user_id_auth_method'), table_name='flow_state', schema='auth')
    op.drop_table('flow_state', schema='auth')
    op.drop_index(op.f('identities_email_idx'), table_name='identities', schema='auth', postgresql_ops={'email': 'text_pattern_ops'})
    op.drop_index(op.f('identities_user_id_idx'), table_name='identities', schema='auth')
    op.drop_table('identities', schema='auth')
    op.drop_table('learning_journeys')
    op.drop_index(op.f('messages_2026_04_13_inserted_at_topic_idx'), table_name='messages_2026_04_13', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_13', schema='realtime')
    op.drop_index(op.f('webauthn_credentials_credential_id_key'), table_name='webauthn_credentials', schema='auth')
    op.drop_index(op.f('webauthn_credentials_user_id_idx'), table_name='webauthn_credentials', schema='auth')
    op.drop_table('webauthn_credentials', schema='auth')
    op.drop_index(op.f('messages_inserted_at_topic_index'), table_name='messages', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages', schema='realtime')
    op.drop_index(op.f('secrets_name_idx'), table_name='secrets', schema='vault', postgresql_where='(name IS NOT NULL)')
    op.drop_table('secrets', schema='vault')
    op.drop_table('user_error_analysis')
    op.drop_table('journey_steps')
    op.drop_index(op.f('confirmation_token_idx'), table_name='users', schema='auth', postgresql_where="((confirmation_token)::text !~ '^[0-9 ]*$'::text)")
    op.drop_index(op.f('email_change_token_current_idx'), table_name='users', schema='auth', postgresql_where="((email_change_token_current)::text !~ '^[0-9 ]*$'::text)")
    op.drop_index(op.f('email_change_token_new_idx'), table_name='users', schema='auth', postgresql_where="((email_change_token_new)::text !~ '^[0-9 ]*$'::text)")
    op.drop_index(op.f('reauthentication_token_idx'), table_name='users', schema='auth', postgresql_where="((reauthentication_token)::text !~ '^[0-9 ]*$'::text)")
    op.drop_index(op.f('recovery_token_idx'), table_name='users', schema='auth', postgresql_where="((recovery_token)::text !~ '^[0-9 ]*$'::text)")
    op.drop_index(op.f('users_email_partial_key'), table_name='users', schema='auth', postgresql_where='(is_sso_user = false)')
    op.drop_index(op.f('users_instance_id_email_idx'), table_name='users', schema='auth')
    op.drop_index(op.f('users_instance_id_idx'), table_name='users', schema='auth')
    op.drop_index(op.f('users_is_anonymous_idx'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('instances', schema='auth')
    op.drop_index(op.f('messages_2026_04_19_inserted_at_topic_idx'), table_name='messages_2026_04_19', schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.drop_table('messages_2026_04_19', schema='realtime')
    op.drop_table('mfa_amr_claims', schema='auth')
    op.drop_index(op.f('oauth_consents_active_client_idx'), table_name='oauth_consents', schema='auth', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('oauth_consents_active_user_client_idx'), table_name='oauth_consents', schema='auth', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('oauth_consents_user_order_idx'), table_name='oauth_consents', schema='auth')
    op.drop_table('oauth_consents', schema='auth')
    op.drop_index(op.f('custom_oauth_providers_created_at_idx'), table_name='custom_oauth_providers', schema='auth')
    op.drop_index(op.f('custom_oauth_providers_enabled_idx'), table_name='custom_oauth_providers', schema='auth')
    op.drop_index(op.f('custom_oauth_providers_identifier_idx'), table_name='custom_oauth_providers', schema='auth')
    op.drop_index(op.f('custom_oauth_providers_provider_type_idx'), table_name='custom_oauth_providers', schema='auth')
    op.drop_table('custom_oauth_providers', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_oauth_providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('acceptable_client_ids', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('pkce_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('authorization_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('email_optional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('issuer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discovery_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skip_nonce_check', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cached_discovery', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discovery_cached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('authorization_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userinfo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jwks_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("authorization_url IS NULL OR authorization_url ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_authorization_url_https')),
    sa.CheckConstraint("identifier ~ '^[a-z0-9][a-z0-9:-]{0,48}[a-z0-9]$'::text", name=op.f('custom_oauth_providers_identifier_format')),
    sa.CheckConstraint("jwks_uri IS NULL OR jwks_uri ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_jwks_uri_https')),
    sa.CheckConstraint("provider_type <> 'oauth2'::text OR authorization_url IS NOT NULL AND token_url IS NOT NULL AND userinfo_url IS NOT NULL", name=op.f('custom_oauth_providers_oauth2_requires_endpoints')),
    sa.CheckConstraint("provider_type <> 'oidc'::text OR discovery_url IS NULL OR discovery_url ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_oidc_discovery_url_https')),
    sa.CheckConstraint("provider_type <> 'oidc'::text OR issuer IS NOT NULL", name=op.f('custom_oauth_providers_oidc_requires_issuer')),
    sa.CheckConstraint("provider_type <> 'oidc'::text OR issuer IS NULL OR issuer ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_oidc_issuer_https')),
    sa.CheckConstraint("provider_type = ANY (ARRAY['oauth2'::text, 'oidc'::text])", name=op.f('custom_oauth_providers_provider_type_check')),
    sa.CheckConstraint("token_url IS NULL OR token_url ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_token_url_https')),
    sa.CheckConstraint("userinfo_url IS NULL OR userinfo_url ~~ 'https://%%'::text", name=op.f('custom_oauth_providers_userinfo_url_https')),
    sa.CheckConstraint('authorization_url IS NULL OR char_length(authorization_url) <= 2048', name=op.f('custom_oauth_providers_authorization_url_length')),
    sa.CheckConstraint('char_length(client_id) >= 1 AND char_length(client_id) <= 512', name=op.f('custom_oauth_providers_client_id_length')),
    sa.CheckConstraint('char_length(name) >= 1 AND char_length(name) <= 100', name=op.f('custom_oauth_providers_name_length')),
    sa.CheckConstraint('discovery_url IS NULL OR char_length(discovery_url) <= 2048', name=op.f('custom_oauth_providers_discovery_url_length')),
    sa.CheckConstraint('issuer IS NULL OR char_length(issuer) >= 1 AND char_length(issuer) <= 2048', name=op.f('custom_oauth_providers_issuer_length')),
    sa.CheckConstraint('jwks_uri IS NULL OR char_length(jwks_uri) <= 2048', name=op.f('custom_oauth_providers_jwks_uri_length')),
    sa.CheckConstraint('token_url IS NULL OR char_length(token_url) <= 2048', name=op.f('custom_oauth_providers_token_url_length')),
    sa.CheckConstraint('userinfo_url IS NULL OR char_length(userinfo_url) <= 2048', name=op.f('custom_oauth_providers_userinfo_url_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_oauth_providers_pkey')),
    sa.UniqueConstraint('identifier', name=op.f('custom_oauth_providers_identifier_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth'
    )
    op.create_index(op.f('custom_oauth_providers_provider_type_idx'), 'custom_oauth_providers', ['provider_type'], unique=False, schema='auth')
    op.create_index(op.f('custom_oauth_providers_identifier_idx'), 'custom_oauth_providers', ['identifier'], unique=False, schema='auth')
    op.create_index(op.f('custom_oauth_providers_enabled_idx'), 'custom_oauth_providers', ['enabled'], unique=False, schema='auth')
    op.create_index(op.f('custom_oauth_providers_created_at_idx'), 'custom_oauth_providers', ['created_at'], unique=False, schema='auth')
    op.create_table('oauth_consents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(TRIM(BOTH FROM scopes)) > 0', name=op.f('oauth_consents_scopes_not_empty')),
    sa.CheckConstraint('char_length(scopes) <= 2048', name=op.f('oauth_consents_scopes_length')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= granted_at', name=op.f('oauth_consents_revoked_after_granted')),
    sa.ForeignKeyConstraint(['client_id'], ['auth.oauth_clients.id'], name=op.f('oauth_consents_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('oauth_consents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_consents_pkey')),
    sa.UniqueConstraint('user_id', 'client_id', name=op.f('oauth_consents_user_client_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth'
    )
    op.create_index(op.f('oauth_consents_user_order_idx'), 'oauth_consents', ['user_id', sa.literal_column('granted_at DESC')], unique=False, schema='auth')
    op.create_index(op.f('oauth_consents_active_user_client_idx'), 'oauth_consents', ['user_id', 'client_id'], unique=False, schema='auth', postgresql_where='(revoked_at IS NULL)')
    op.create_index(op.f('oauth_consents_active_client_idx'), 'oauth_consents', ['client_id'], unique=False, schema='auth', postgresql_where='(revoked_at IS NULL)')
    op.create_table('mfa_amr_claims',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('authentication_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['auth.sessions.id'], name=op.f('mfa_amr_claims_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('amr_id_pk')),
    sa.UniqueConstraint('session_id', 'authentication_method', name=op.f('mfa_amr_claims_session_id_authentication_method_pkey'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='auth: stores authenticator method reference claims for multi factor authentication'
    )
    op.create_table('messages_2026_04_19',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_19_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_19_inserted_at_topic_idx'), 'messages_2026_04_19', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_base_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('instances_pkey')),
    schema='auth',
    comment='Auth: Manages users across multiple sites.'
    )
    op.create_table('users',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aud', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('encrypted_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confirmation_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confirmation_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('recovery_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recovery_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email_change_token_new', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_change', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_change_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_sign_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('raw_app_meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_user_meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('phone_confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('phone_change', sa.TEXT(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_change_token', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_change_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), sa.Computed('LEAST(email_confirmed_at, phone_confirmed_at)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('email_change_token_current', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('email_change_confirm_status', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reauthentication_token', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('reauthentication_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_sso_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint('email_change_confirm_status >= 0 AND email_change_confirm_status <= 2', name=op.f('users_email_change_confirm_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Stores user login data within a secure schema.'
    )
    op.create_index(op.f('users_is_anonymous_idx'), 'users', ['is_anonymous'], unique=False, schema='auth')
    op.create_index(op.f('users_instance_id_idx'), 'users', ['instance_id'], unique=False, schema='auth')
    op.create_index(op.f('users_instance_id_email_idx'), 'users', ['instance_id', sa.literal_column('lower(email::text)')], unique=False, schema='auth')
    op.create_index(op.f('users_email_partial_key'), 'users', ['email'], unique=True, schema='auth', postgresql_where='(is_sso_user = false)')
    op.create_index(op.f('recovery_token_idx'), 'users', ['recovery_token'], unique=True, schema='auth', postgresql_where="((recovery_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('reauthentication_token_idx'), 'users', ['reauthentication_token'], unique=True, schema='auth', postgresql_where="((reauthentication_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('email_change_token_new_idx'), 'users', ['email_change_token_new'], unique=True, schema='auth', postgresql_where="((email_change_token_new)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('email_change_token_current_idx'), 'users', ['email_change_token_current'], unique=True, schema='auth', postgresql_where="((email_change_token_current)::text !~ '^[0-9 ]*$'::text)")
    op.create_index(op.f('confirmation_token_idx'), 'users', ['confirmation_token'], unique=True, schema='auth', postgresql_where="((confirmation_token)::text !~ '^[0-9 ]*$'::text)")
    op.create_table('journey_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('journey_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'locked'::text"), autoincrement=False, nullable=True),
    sa.Column('skill_focus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('icon_type', sa.TEXT(), server_default=sa.text("'map-pin'::text"), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['learning_journeys.id'], name=op.f('fk_journey_steps_journey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journey_steps_pkey'))
    )
    op.create_table('user_error_analysis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_interpretation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('error_profile_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['error_profile_id'], ['user_error_profiles.user_id'], name=op.f('user_error_analysis_error_profile_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank_items.id'], name=op.f('user_error_analysis_question_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('user_error_analysis_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_error_analysis_pkey'))
    )
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nonce', postgresql.BYTEA(), server_default=sa.text('vault._crypto_aead_det_noncegen()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('secrets_pkey')),
    schema='vault',
    comment='Table with encrypted `secret` column for storing sensitive information on disk.'
    )
    op.create_index(op.f('secrets_name_idx'), 'secrets', ['name'], unique=True, schema='vault', postgresql_where='(name IS NOT NULL)')
    op.create_table('messages',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_inserted_at_topic_index'), 'messages', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credential_id', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('attestation_type', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('aaguid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sign_count', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('backup_eligible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('backed_up', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('friendly_name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('webauthn_credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('webauthn_credentials_pkey')),
    schema='auth'
    )
    op.create_index(op.f('webauthn_credentials_user_id_idx'), 'webauthn_credentials', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('webauthn_credentials_credential_id_key'), 'webauthn_credentials', ['credential_id'], unique=True, schema='auth')
    op.create_table('messages_2026_04_13',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_13_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_13_inserted_at_topic_idx'), 'messages_2026_04_13', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('learning_journeys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('current_node_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('learning_journeys_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_journeys_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('learning_journeys_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('identities',
    sa.Column('provider_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('identity_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_sign_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), sa.Computed("lower((identity_data ->> 'email'::text))", persisted=True), autoincrement=False, nullable=True, comment='Auth: Email is a generated column that references the optional email property in the identity_data'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('identities_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identities_pkey')),
    sa.UniqueConstraint('provider_id', 'provider', name=op.f('identities_provider_id_provider_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Stores identities associated to a user.'
    )
    op.create_index(op.f('identities_user_id_idx'), 'identities', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('identities_email_idx'), 'identities', ['email'], unique=False, schema='auth', postgresql_ops={'email': 'text_pattern_ops'})
    op.create_table('flow_state',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('auth_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_challenge_method', postgresql.ENUM('s256', 'plain', name='code_challenge_method', schema='auth'), autoincrement=False, nullable=True),
    sa.Column('code_challenge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('authentication_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_code_issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('invite_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oauth_client_state_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('linking_target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email_optional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('flow_state_pkey')),
    schema='auth',
    comment='Stores metadata for all OAuth/SSO login flows'
    )
    op.create_index(op.f('idx_user_id_auth_method'), 'flow_state', ['user_id', 'authentication_method'], unique=False, schema='auth')
    op.create_index(op.f('idx_auth_code'), 'flow_state', ['auth_code'], unique=False, schema='auth')
    op.create_index(op.f('flow_state_created_at_idx'), 'flow_state', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('oauth_authorizations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('authorization_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('redirect_uri', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_challenge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_challenge_method', postgresql.ENUM('s256', 'plain', name='code_challenge_method', schema='auth'), autoincrement=False, nullable=True),
    sa.Column('response_type', postgresql.ENUM('code', name='oauth_response_type', schema='auth'), server_default=sa.text("'code'::auth.oauth_response_type"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'denied', 'expired', name='oauth_authorization_status', schema='auth'), server_default=sa.text("'pending'::auth.oauth_authorization_status"), autoincrement=False, nullable=False),
    sa.Column('authorization_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() + '00:03:00'::interval)"), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nonce', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(authorization_code) <= 255', name=op.f('oauth_authorizations_authorization_code_length')),
    sa.CheckConstraint('char_length(code_challenge) <= 128', name=op.f('oauth_authorizations_code_challenge_length')),
    sa.CheckConstraint('char_length(nonce) <= 255', name=op.f('oauth_authorizations_nonce_length')),
    sa.CheckConstraint('char_length(redirect_uri) <= 2048', name=op.f('oauth_authorizations_redirect_uri_length')),
    sa.CheckConstraint('char_length(resource) <= 2048', name=op.f('oauth_authorizations_resource_length')),
    sa.CheckConstraint('char_length(scope) <= 4096', name=op.f('oauth_authorizations_scope_length')),
    sa.CheckConstraint('char_length(state) <= 4096', name=op.f('oauth_authorizations_state_length')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('oauth_authorizations_expires_at_future')),
    sa.ForeignKeyConstraint(['client_id'], ['auth.oauth_clients.id'], name=op.f('oauth_authorizations_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('oauth_authorizations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_authorizations_pkey')),
    sa.UniqueConstraint('authorization_code', name=op.f('oauth_authorizations_authorization_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('authorization_id', name=op.f('oauth_authorizations_authorization_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth'
    )
    op.create_index(op.f('oauth_auth_pending_exp_idx'), 'oauth_authorizations', ['expires_at'], unique=False, schema='auth', postgresql_where="(status = 'pending'::auth.oauth_authorization_status)")
    op.create_table('objects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True, comment='Field is deprecated, use owner_id instead'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('path_tokens', postgresql.ARRAY(sa.TEXT()), sa.Computed("string_to_array(name, '/'::text)", persisted=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name=op.f('objects_bucketId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('objects_pkey')),
    schema='storage'
    )
    op.create_index(op.f('name_prefix_search'), 'objects', ['name'], unique=False, schema='storage', postgresql_ops={'name': 'text_pattern_ops'})
    op.create_index(op.f('idx_objects_bucket_id_name_lower'), 'objects', ['bucket_id', sa.literal_column('lower(name)')], unique=False, schema='storage')
    op.create_index(op.f('idx_objects_bucket_id_name'), 'objects', ['bucket_id', 'name'], unique=False, schema='storage')
    op.create_index(op.f('bucketid_objname'), 'objects', ['bucket_id', 'name'], unique=True, schema='storage')
    op.create_table('oauth_clients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_secret_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registration_type', postgresql.ENUM('dynamic', 'manual', name='oauth_registration_type', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('redirect_uris', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('grant_types', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('client_type', postgresql.ENUM('public', 'confidential', name='oauth_client_type', schema='auth'), server_default=sa.text("'confidential'::auth.oauth_client_type"), autoincrement=False, nullable=False),
    sa.Column('token_endpoint_auth_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("token_endpoint_auth_method = ANY (ARRAY['client_secret_basic'::text, 'client_secret_post'::text, 'none'::text])", name=op.f('oauth_clients_token_endpoint_auth_method_check')),
    sa.CheckConstraint('char_length(client_name) <= 1024', name=op.f('oauth_clients_client_name_length')),
    sa.CheckConstraint('char_length(client_uri) <= 2048', name=op.f('oauth_clients_client_uri_length')),
    sa.CheckConstraint('char_length(logo_uri) <= 2048', name=op.f('oauth_clients_logo_uri_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_clients_pkey')),
    schema='auth'
    )
    op.create_index(op.f('oauth_clients_deleted_at_idx'), 'oauth_clients', ['deleted_at'], unique=False, schema='auth')
    op.create_table('oauth_client_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code_verifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_client_states_pkey')),
    schema='auth',
    comment='Stores OAuth states for third-party provider authentication flows where Supabase acts as the OAuth client.'
    )
    op.create_index(op.f('idx_oauth_client_states_created_at'), 'oauth_client_states', ['created_at'], unique=False, schema='auth')
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('challenge_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("challenge_type = ANY (ARRAY['signup'::text, 'registration'::text, 'authentication'::text])", name=op.f('webauthn_challenges_challenge_type_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('webauthn_challenges_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('webauthn_challenges_pkey')),
    schema='auth'
    )
    op.create_index(op.f('webauthn_challenges_user_id_idx'), 'webauthn_challenges', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('webauthn_challenges_expires_at_idx'), 'webauthn_challenges', ['expires_at'], unique=False, schema='auth')
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey')),
    schema='auth',
    comment='Auth: Manages updates to the auth system.'
    )
    op.create_table('messages_2026_04_18',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_18_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_18_inserted_at_topic_idx'), 'messages_2026_04_18', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('user', 'admin', name='user_role'), server_default=sa.text("'user'::user_role"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('messages_2026_04_17',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_17_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_17_inserted_at_topic_idx'), 'messages_2026_04_17', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('messages_2026_04_14',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_14_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_14_inserted_at_topic_idx'), 'messages_2026_04_14', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('messages_2026_04_16',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_16_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_16_inserted_at_topic_idx'), 'messages_2026_04_16', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('mfa_challenges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('web_authn_session_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['auth.mfa_factors.id'], name=op.f('mfa_challenges_auth_factor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mfa_challenges_pkey')),
    schema='auth',
    comment='auth: stores metadata about challenge requests made'
    )
    op.create_index(op.f('mfa_challenge_created_at_idx'), 'mfa_challenges', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('refresh_tokens',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('parent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth.sessions.id'], name=op.f('refresh_tokens_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('refresh_tokens_token_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Store of tokens used to refresh JWT tokens once they expire.'
    )
    op.create_index(op.f('refresh_tokens_updated_at_idx'), 'refresh_tokens', [sa.literal_column('updated_at DESC')], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_session_id_revoked_idx'), 'refresh_tokens', ['session_id', 'revoked'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_parent_idx'), 'refresh_tokens', ['parent'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_instance_id_user_id_idx'), 'refresh_tokens', ['instance_id', 'user_id'], unique=False, schema='auth')
    op.create_index(op.f('refresh_tokens_instance_id_idx'), 'refresh_tokens', ['instance_id'], unique=False, schema='auth')
    op.create_table('vector_indexes',
    sa.Column('id', sa.TEXT(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(collation='C'), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance_metric', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets_vectors.id'], name=op.f('vector_indexes_bucket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_indexes_pkey')),
    schema='storage'
    )
    op.create_index(op.f('vector_indexes_name_bucket_id_idx'), 'vector_indexes', ['name', 'bucket_id'], unique=True, schema='storage')
    op.create_table('s3_multipart_uploads',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('in_progress_size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('upload_signature', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(collation='C'), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name=op.f('s3_multipart_uploads_bucket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('s3_multipart_uploads_pkey')),
    schema='storage'
    )
    op.create_index(op.f('idx_multipart_uploads_list'), 's3_multipart_uploads', ['bucket_id', 'key', 'created_at'], unique=False, schema='storage')
    op.create_table('question_bank_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('skill', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stimulus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sub_skill', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('question_bank_items_pkey'))
    )
    op.create_table('user_error_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('user_error_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_error_profiles_pkey'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'in_progress'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('assessments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessments_pkey'))
    )
    op.create_table('learner_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_level', sa.TEXT(), server_default=sa.text("'A1'::text"), autoincrement=False, nullable=True),
    sa.Column('onboarding_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('has_completed_assessment', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('learner_profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_profiles_pkey'))
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('migrations_pkey')),
    sa.UniqueConstraint('name', name=op.f('migrations_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='storage'
    )
    op.create_table('subscription',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity', postgresql.REGCLASS(), autoincrement=False, nullable=False),
    sa.Column('filters', sa.NullType(), server_default=sa.text("'{}'::realtime.user_defined_filter[]"), autoincrement=False, nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('claims_role', sa.NullType(), sa.Computed("realtime.to_regrole((claims ->> 'role'::text))", persisted=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('action_filter', sa.TEXT(), server_default=sa.text("'*'::text"), autoincrement=False, nullable=True),
    sa.CheckConstraint("action_filter = ANY (ARRAY['*'::text, 'INSERT'::text, 'UPDATE'::text, 'DELETE'::text])", name=op.f('subscription_action_filter_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription')),
    schema='realtime'
    )
    op.create_index(op.f('subscription_subscription_id_entity_filters_action_filter_key'), 'subscription', ['subscription_id', 'entity', 'filters', 'action_filter'], unique=True, schema='realtime')
    op.create_index(op.f('ix_realtime_subscription_entity'), 'subscription', ['entity'], unique=False, schema='realtime')
    op.create_table('one_time_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_type', postgresql.ENUM('confirmation_token', 'reauthentication_token', 'recovery_token', 'email_change_token_new', 'email_change_token_current', 'phone_change_token', name='one_time_token_type', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('relates_to', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(token_hash) > 0', name=op.f('one_time_tokens_token_hash_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('one_time_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('one_time_tokens_pkey')),
    schema='auth'
    )
    op.create_index(op.f('one_time_tokens_user_id_token_type_key'), 'one_time_tokens', ['user_id', 'token_type'], unique=True, schema='auth')
    op.create_index(op.f('one_time_tokens_token_hash_hash_idx'), 'one_time_tokens', ['token_hash'], unique=False, schema='auth', postgresql_using='hash')
    op.create_index(op.f('one_time_tokens_relates_to_hash_idx'), 'one_time_tokens', ['relates_to'], unique=False, schema='auth', postgresql_using='hash')
    op.create_table('s3_multipart_uploads_parts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('part_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bucket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(collation='C'), autoincrement=False, nullable=False),
    sa.Column('etag', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['storage.buckets.id'], name=op.f('s3_multipart_uploads_parts_bucket_id_fkey')),
    sa.ForeignKeyConstraint(['upload_id'], ['storage.s3_multipart_uploads.id'], name=op.f('s3_multipart_uploads_parts_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('s3_multipart_uploads_parts_pkey')),
    schema='storage'
    )
    op.create_table('saml_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_xml', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name_id_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(entity_id) > 0', name=op.f('entity_id not empty')),
    sa.CheckConstraint('char_length(metadata_xml) > 0', name=op.f('metadata_xml not empty')),
    sa.CheckConstraint('metadata_url = NULL::text OR char_length(metadata_url) > 0', name=op.f('metadata_url not empty')),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('saml_providers_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saml_providers_pkey')),
    sa.UniqueConstraint('entity_id', name=op.f('saml_providers_entity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='Auth: Manages SAML Identity Provider connections.'
    )
    op.create_index(op.f('saml_providers_sso_provider_id_idx'), 'saml_providers', ['sso_provider_id'], unique=False, schema='auth')
    op.create_table('saml_relay_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('for_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('redirect_to', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('flow_state_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(request_id) > 0', name=op.f('request_id not empty')),
    sa.ForeignKeyConstraint(['flow_state_id'], ['auth.flow_state.id'], name=op.f('saml_relay_states_flow_state_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('saml_relay_states_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saml_relay_states_pkey')),
    schema='auth',
    comment='Auth: Contains SAML Relay State information for each Service Provider initiated login.'
    )
    op.create_index(op.f('saml_relay_states_sso_provider_id_idx'), 'saml_relay_states', ['sso_provider_id'], unique=False, schema='auth')
    op.create_index(op.f('saml_relay_states_for_email_idx'), 'saml_relay_states', ['for_email'], unique=False, schema='auth')
    op.create_index(op.f('saml_relay_states_created_at_idx'), 'saml_relay_states', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('badge_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('user_achievements_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_achievements_pkey'))
    )
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('predicted_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skill', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('assessment_responses_assessment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank_items.id'], name=op.f('assessment_responses_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('assessment_responses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_responses_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey')),
    schema='realtime'
    )
    op.create_table('buckets_vectors',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STANDARD', 'ANALYTICS', 'VECTOR', name='buckettype', schema='storage'), server_default=sa.text("'VECTOR'::storage.buckettype"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('buckets_vectors_pkey')),
    schema='storage'
    )
    op.create_table('messages_2026_04_15',
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_at', name=op.f('messages_2026_04_15_pkey')),
    schema='realtime'
    )
    op.create_index(op.f('messages_2026_04_15_inserted_at_topic_idx'), 'messages_2026_04_15', [sa.literal_column('inserted_at DESC'), 'topic'], unique=False, schema='realtime', postgresql_where="((extension = 'broadcast'::text) AND (private IS TRUE))")
    op.create_table('sso_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.TEXT(), autoincrement=False, nullable=True, comment='Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.CheckConstraint('resource_id = NULL::text OR char_length(resource_id) > 0', name=op.f('resource_id not empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('sso_providers_pkey')),
    schema='auth',
    comment='Auth: Manages SSO identity provider information; see saml_providers for SAML.'
    )
    op.create_index(op.f('sso_providers_resource_id_pattern_idx'), 'sso_providers', ['resource_id'], unique=False, schema='auth', postgresql_ops={'resource_id': 'text_pattern_ops'})
    op.create_index(op.f('sso_providers_resource_id_idx'), 'sso_providers', [sa.literal_column('lower(resource_id)')], unique=True, schema='auth')
    op.create_table('buckets_analytics',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STANDARD', 'ANALYTICS', 'VECTOR', name='buckettype', schema='storage'), server_default=sa.text("'ANALYTICS'::storage.buckettype"), autoincrement=False, nullable=False),
    sa.Column('format', sa.TEXT(), server_default=sa.text("'ICEBERG'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('buckets_analytics_pkey')),
    schema='storage'
    )
    op.create_index(op.f('buckets_analytics_unique_name_idx'), 'buckets_analytics', ['name'], unique=True, schema='storage', postgresql_where='(deleted_at IS NULL)')
    op.create_table('buckets',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True, comment='Field is deprecated, use owner_id instead'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('avif_autodetection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('file_size_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('allowed_mime_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('STANDARD', 'ANALYTICS', 'VECTOR', name='buckettype', schema='storage'), server_default=sa.text("'STANDARD'::storage.buckettype"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('buckets_pkey')),
    schema='storage'
    )
    op.create_index(op.f('bname'), 'buckets', ['name'], unique=True, schema='storage')
    op.create_table('skill_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('current_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.TEXT(), server_default=sa.text("'A1'::text"), autoincrement=False, nullable=True),
    sa.Column('last_tested', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner_profiles.id'], name=op.f('skill_states_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_states_pkey')),
    sa.UniqueConstraint('user_id', 'skill_name', name=op.f('unique_user_skill'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('mfa_factors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('friendly_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('factor_type', postgresql.ENUM('totp', 'webauthn', 'phone', name='factor_type', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('unverified', 'verified', name='factor_status', schema='auth'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_challenged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('web_authn_credential', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('web_authn_aaguid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_webauthn_challenge_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Stores the latest WebAuthn challenge data including attestation/assertion for customer verification'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('mfa_factors_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mfa_factors_pkey')),
    sa.UniqueConstraint('last_challenged_at', name=op.f('mfa_factors_last_challenged_at_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth',
    comment='auth: stores metadata about factors'
    )
    op.create_index(op.f('unique_phone_factor_per_user'), 'mfa_factors', ['user_id', 'phone'], unique=True, schema='auth')
    op.create_index(op.f('mfa_factors_user_id_idx'), 'mfa_factors', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('mfa_factors_user_friendly_name_unique'), 'mfa_factors', ['friendly_name', 'user_id'], unique=True, schema='auth', postgresql_where="(TRIM(BOTH FROM friendly_name) <> ''::text)")
    op.create_index(op.f('factor_id_created_at_idx'), 'mfa_factors', ['user_id', 'created_at'], unique=False, schema='auth')
    op.create_table('audit_log_entries',
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_entries_pkey')),
    schema='auth',
    comment='Auth: Audit trail for user actions.'
    )
    op.create_index(op.f('audit_logs_instance_id_idx'), 'audit_log_entries', ['instance_id'], unique=False, schema='auth')
    op.create_table('sso_domains',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sso_provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(domain) > 0', name=op.f('domain not empty')),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['auth.sso_providers.id'], name=op.f('sso_domains_sso_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sso_domains_pkey')),
    schema='auth',
    comment='Auth: Manages SSO email address domain mapping to an SSO Identity Provider.'
    )
    op.create_index(op.f('sso_domains_sso_provider_id_idx'), 'sso_domains', ['sso_provider_id'], unique=False, schema='auth')
    op.create_index(op.f('sso_domains_domain_idx'), 'sso_domains', [sa.literal_column('lower(domain)')], unique=True, schema='auth')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aal', postgresql.ENUM('aal1', 'aal2', 'aal3', name='aal_level', schema='auth'), autoincrement=False, nullable=True),
    sa.Column('not_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.'),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oauth_client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('refresh_token_hmac_key', sa.TEXT(), autoincrement=False, nullable=True, comment='Holds a HMAC-SHA256 key used to sign refresh tokens for this session.'),
    sa.Column('refresh_token_counter', sa.BIGINT(), autoincrement=False, nullable=True, comment='Holds the ID (counter) of the last issued refresh token.'),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(scopes) <= 4096', name=op.f('sessions_scopes_length')),
    sa.ForeignKeyConstraint(['oauth_client_id'], ['auth.oauth_clients.id'], name=op.f('sessions_oauth_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    schema='auth',
    comment='Auth: Stores session data associated to a user.'
    )
    op.create_index(op.f('user_id_created_at_idx'), 'sessions', ['user_id', 'created_at'], unique=False, schema='auth')
    op.create_index(op.f('sessions_user_id_idx'), 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('sessions_oauth_client_id_idx'), 'sessions', ['oauth_client_id'], unique=False, schema='auth')
    op.create_index(op.f('sessions_not_after_idx'), 'sessions', [sa.literal_column('not_after DESC')], unique=False, schema='auth')
    # ### end Alembic commands ###
