"""final_dashboard_schema_sync

Revision ID: 647772ddec5b
Revises: cd6834c5654a
Create Date: 2026-04-17 23:16:46.624845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '647772ddec5b'
down_revision: Union[str, Sequence[str], None] = 'cd6834c5654a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. New Table: User Achievements
    op.create_table('user_achievements',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('badge_name', sa.String(), nullable=False),
        sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Skill States: Rename & Add (Preserving Data)
    # Rename score to current_score
    op.alter_column('skill_states', 'score', new_column_name='current_score')
    # Rename last_updated to updated_at
    op.alter_column('skill_states', 'last_updated', new_column_name='updated_at')
    # Add new columns
    op.add_column('skill_states', sa.Column('current_level', sa.String(), nullable=True, server_default='A1'))
    op.add_column('skill_states', sa.Column('confidence', sa.Float(), nullable=True, server_default='0.0'))

    # 3. User Error Analysis: Add Metrics
    op.add_column('user_error_analysis', sa.Column('error_rate', sa.Float(), nullable=True, server_default='0.0'))

    # 4. User Error Profile: Add Dashboard Fields
    op.add_column('user_error_profiles', sa.Column('common_mistakes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('user_error_profiles', sa.Column('bridge_delta', sa.String(), nullable=True))
    op.add_column('user_error_profiles', sa.Column('bridge_percentage', sa.Float(), nullable=True, server_default='0.0'))

    # 5. Force Schema Reload (Supabase/PostgREST cache refresh)
    op.execute("NOTIFY pgrst, 'reload schema'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('user_error_profiles', 'bridge_percentage')
    op.drop_column('user_error_profiles', 'bridge_delta')
    op.drop_column('user_error_profiles', 'common_mistakes')
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('user_error_analysis', 'error_rate')
    op.add_column('skill_states', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skill_states', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('skill_states', 'updated_at')
    op.drop_column('skill_states', 'confidence')
    op.drop_column('skill_states', 'current_score')
    op.drop_column('skill_states', 'current_level')
    op.alter_column('learning_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('journey_steps', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('journey_steps', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_responses', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
