"""decouple_xp_cefr

Revision ID: 64bc769aad78
Revises: 981a85a72312
Create Date: 2026-04-18 14:51:02.291108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64bc769aad78'
down_revision: Union[str, Sequence[str], None] = '981a85a72312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('xp_points', sa.Integer(), nullable=True))
    op.add_column('learner_profiles', sa.Column('current_proficiency_level', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('proficiency_confidence', sa.Float(), nullable=True))
    op.add_column('learner_profiles', sa.Column('stability_buffer', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('skill_states', sa.Column('xp_points', sa.Integer(), nullable=True))
    op.add_column('skill_states', sa.Column('current_proficiency_level', sa.String(), nullable=True))
    op.add_column('skill_states', sa.Column('proficiency_confidence', sa.Float(), nullable=True))
    op.add_column('skill_states', sa.Column('stability_buffer', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_states', 'stability_buffer')
    op.drop_column('skill_states', 'proficiency_confidence')
    op.drop_column('skill_states', 'current_proficiency_level')
    op.drop_column('skill_states', 'xp_points')
    op.drop_column('learner_profiles', 'stability_buffer')
    op.drop_column('learner_profiles', 'proficiency_confidence')
    op.drop_column('learner_profiles', 'current_proficiency_level')
    op.drop_column('learner_profiles', 'xp_points')
    # ### end Alembic commands ###
