"""add user_skills table

Revision ID: 7a551e8a5e94
Revises: a4834af2c12d
Create Date: 2026-04-17 18:04:29.505485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a551e8a5e94'
down_revision: Union[str, Sequence[str], None] = 'a4834af2c12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='uq_user_skill')
    )
    op.add_column('assessments', sa.Column('total_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'total_questions')
    op.drop_table('user_skills')
    # ### end Alembic commands ###
