"""Add missing frontend columns to learner_profiles

Revision ID: 8d166c9ab252
Revises: 70032a46c503
Create Date: 2026-04-17 16:19:17.124199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d166c9ab252'
down_revision: Union[str, Sequence[str], None] = '70032a46c503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('focus_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('learner_profiles', sa.Column('learning_goal', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('goal_context', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('learning_topics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('learner_profiles', sa.Column('session_intensity', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('native_language', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('target_language', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('streak', sa.Integer(), server_default='0', nullable=True))
    op.add_column('learner_profiles', sa.Column('pacing_score', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('learner_profiles', sa.Column('accuracy_rate', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('learner_profiles', sa.Column('self_correction_rate', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('learner_profiles', sa.Column('confidence_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_profiles', 'confidence_style')
    op.drop_column('learner_profiles', 'self_correction_rate')
    op.drop_column('learner_profiles', 'accuracy_rate')
    op.drop_column('learner_profiles', 'pacing_score')
    op.drop_column('learner_profiles', 'streak')
    op.drop_column('learner_profiles', 'target_language')
    op.drop_column('learner_profiles', 'native_language')
    op.drop_column('learner_profiles', 'session_intensity')
    op.drop_column('learner_profiles', 'learning_topics')
    op.drop_column('learner_profiles', 'goal_context')
    op.drop_column('learner_profiles', 'learning_goal')
    op.drop_column('learner_profiles', 'focus_skills')
    # ### end Alembic commands ###
