"""Add extended metrics to learner_profiles

Revision ID: 981a85a72312
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 00:30:48.484420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '981a85a72312'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assessment_responses', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_responses', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journey_steps', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journey_steps', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=True)
    op.add_column('learner_profiles', sa.Column('average_response_time', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('learner_profiles', sa.Column('total_questions_answered', sa.Integer(), server_default='0', nullable=True))
    op.add_column('learner_profiles', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_states', 'current_level',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('skill_states', 'level',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('skill_states', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_error_analysis', 'error_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_error_profiles', 'bridge_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_error_profiles', 'bridge_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_error_analysis', 'error_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('skill_states', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('skill_states', 'level',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'A1'::character varying"),
               existing_nullable=True)
    op.alter_column('skill_states', 'current_level',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'A1'::character varying"),
               existing_nullable=True)
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learning_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('learner_profiles', 'last_active_at')
    op.drop_column('learner_profiles', 'total_questions_answered')
    op.drop_column('learner_profiles', 'average_response_time')
    op.alter_column('journey_steps', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('journey_steps', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_responses', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
