"""rename_skills_to_skill_states

Revision ID: baef726e84b4
Revises: f1a2b3c4d5e6
Create Date: 2026-04-17 23:09:31.749134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baef726e84b4'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Rename Table
    op.rename_table('user_skills', 'skill_states')
    
    # 2. Rename Column
    op.alter_column('skill_states', 'skill_name', new_column_name='skill')
    
    # 3. Update Unique Constraint
    # In some versions of Alembic/Postgres, we might need to drop and re-create the unique constraint
    op.drop_constraint('uq_user_skill', 'skill_states', type_='unique')
    op.create_unique_constraint('uq_user_skill', 'skill_states', ['user_id', 'skill'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learning_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('journey_steps', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_responses', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('user_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('user_skills_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_skills_pkey')),
    sa.UniqueConstraint('user_id', 'skill_name', name=op.f('uq_user_skill'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('skill_states')
    # ### end Alembic commands ###
