"""add_journey_columns_and_reload_cache

Revision ID: cd6834c5654a
Revises: baef726e84b4
Create Date: 2026-04-17 23:13:25.261200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd6834c5654a'
down_revision: Union[str, Sequence[str], None] = 'baef726e84b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add missing Journey Step columns
    op.add_column('journey_steps', sa.Column('description', sa.String(), nullable=True))
    op.add_column('journey_steps', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('journey_steps', sa.Column('icon_type', sa.String(), nullable=True))
    op.add_column('journey_steps', sa.Column('skill_focus', sa.String(), nullable=True))
    op.add_column('journey_steps', sa.Column('is_locked', sa.Boolean(), nullable=True))
    
    # 2. Add missing Learning Journey columns
    op.add_column('learning_journeys', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('learning_journeys', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True))

    # 3. Force Schema Reload (Supabase/PostgREST cache refresh)
    # This ensures Postgres notifies PostgREST to reload its schema cache immediately.
    op.execute("NOTIFY pgrst, 'reload schema'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('learning_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('learning_journeys', 'updated_at')
    op.drop_column('learning_journeys', 'metadata')
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('journey_steps', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('journey_steps', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('journey_steps', 'is_locked')
    op.drop_column('journey_steps', 'skill_focus')
    op.drop_column('journey_steps', 'icon_type')
    op.drop_column('journey_steps', 'order_index')
    op.drop_column('journey_steps', 'description')
    op.alter_column('assessments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_responses', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
