"""Add structured progression fields and LevelConfig

Revision ID: d7201e380f57
Revises: 6d8df2b5e1eb
Create Date: 2026-05-12 21:49:37.944500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7201e380f57'
down_revision: Union[str, Sequence[str], None] = '6d8df2b5e1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels_config',
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('nodes_per_chapter', sa.Integer(), nullable=True),
    sa.Column('min_pass_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('level_name')
    )
    op.drop_table('team_invites')
    op.drop_table('audit_logs')
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('assessment_responses', 'question_level')
    op.alter_column('daily_content', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('journey_steps', sa.Column('completion_accuracy', sa.Float(), nullable=True))
    op.add_column('journey_steps', sa.Column('is_repair_node', sa.Boolean(), nullable=True))
    op.add_column('learner_profiles', sa.Column('current_level_xp', sa.Integer(), nullable=True))
    op.add_column('learner_profiles', sa.Column('is_gateway_unlocked', sa.Boolean(), nullable=True))
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('learner_profiles', 'current_proficiency')
    op.drop_column('learner_profiles', 'points')
    op.drop_column('learner_profiles', 'milestone_progress')
    op.drop_column('learner_profiles', 'skill_distribution')
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_profiles_role'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_team_id'), table_name='profiles')
    op.drop_column('profiles', 'last_seen_at')
    op.drop_column('profiles', 'is_team_leader')
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='task_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::task_status"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.alter_column('teams', 'team_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_error_profile_user_id'), 'user_error_profiles', type_='unique')
    op.alter_column('weekly_vocabulary', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('weekly_vocabulary', 'day_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=Saturday, 1=Sunday, ..., 6=Friday',
               existing_nullable=False)
    op.alter_column('weekly_vocabulary', 'week_start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='The Saturday this cycle belongs to',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_vocabulary', 'week_start_date',
               existing_type=sa.DATE(),
               comment='The Saturday this cycle belongs to',
               existing_nullable=False)
    op.alter_column('weekly_vocabulary', 'day_index',
               existing_type=sa.INTEGER(),
               comment='0=Saturday, 1=Sunday, ..., 6=Friday',
               existing_nullable=False)
    op.alter_column('weekly_vocabulary', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_user_error_profile_user_id'), 'user_error_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_error_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_error_analysis', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'team_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('idx_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'in_progress', 'completed', name='task_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::task_status"))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('skill_states', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('is_team_leader', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_profiles_team_id'), 'profiles', ['team_id'], unique=False)
    op.create_index(op.f('idx_profiles_role'), 'profiles', ['role'], unique=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('learner_profiles', sa.Column('skill_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('learner_profiles', sa.Column('milestone_progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('learner_profiles', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('learner_profiles', sa.Column('current_proficiency', sa.TEXT(), server_default=sa.text("'A1'::text"), autoincrement=False, nullable=True))
    op.alter_column('learner_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('learner_profiles', 'is_gateway_unlocked')
    op.drop_column('learner_profiles', 'current_level_xp')
    op.drop_column('journey_steps', 'is_repair_node')
    op.drop_column('journey_steps', 'completion_accuracy')
    op.alter_column('daily_content', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('assessment_responses', sa.Column('question_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('assessment_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assessment_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], name=op.f('audit_logs_admin_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['profiles.id'], name=op.f('audit_logs_target_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], name=op.f('team_invites_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_invites_team_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['profiles.id'], name=op.f('team_invites_used_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_invites_pkey')),
    sa.UniqueConstraint('token', name=op.f('team_invites_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('levels_config')
    # ### end Alembic commands ###
